name: hive_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs), backed by a Hive store.
version: 3.0.1
homepage: https://github.com/cachapa/hive_crdt
repository: https://github.com/cachapa/hive_crdt
issue_tracker: https://github.com/cachapa/hive_crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crdt: ^5.0.2
#    path: ../crdt
  hive: ^2.2.3

dev_dependencies:
  lints: any
  test: any
  uuid: any
